version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./2021-09-04_composition-assignment-2-problem/:/app
