version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./2021-09-06_composition-19-vuex-starting-project/:/app
